#version: '2'
#
#networks:
#  app-tier:
#    driver: bridge
#
#services:
#  zookeeper:
#    image: 'bitnami/zookeeper:latest'
#    networks:
#      - app-tier
#  kafka:
#    image: 'bitnami/kafka:latest'
#    networks:
#      - app-tier
#  myapp:
#    image: 'YOUR_APPLICATION_IMAGE'
#    networks:
#      - app-tier


version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  db:
    image: postgres
    container_name: kafka_transactions
    restart: always
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432