server:
  port: 9000

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: verificationResult
        input:
          destination: transactionsQueue
          group: transactionsGroup
      default:
        contentType: application/json
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
    producer:
      bootstrap-servers: localhost:9092
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: false
    out-of-order: true
    enabled: true
    locations: classpath:database/migration
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/transactions
    username: user
    password: password
    testOnBorrow: true
    validationQuery: SELECT 1
    hikari:
      maximumPoolSize: 50
      idleTimeout: 600000
      connectionTimeout: 100000
      validationTimeout: 5000
      maxLifetime: 1800000